name: Executar Script Python

on:
  schedule:
    - cron: '0 15 * * *'  # Executa todos os dias às 12:15 UTC (09:15 no horário de Brasília)
  workflow_dispatch:        # Permite execução manual também, se quiser
  # push:
  #   branches: [main]        # Opcional, caso queira continuar executando no push

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'  # Troque pela versão que preferir

      - name: Instalar dependências
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Executar script
        run: |
          python main.py
